/*--------------------------------------------------------------------------*/
/* Copyright 2024 NXP                                                       */
/*                                                                          */
/* NXP Confidential and Proprietary. This software is owned or controlled   */
/* by NXP and may only be used strictly in accordance with the applicable   */
/* license terms.  By expressly accepting such terms or by downloading,     */
/* installing, activating and/or otherwise using the software, you are      */
/* agreeing that you have read, and that you agree to comply with and are   */
/* bound by, such license terms.  If you do not agree to be bound by the    */
/* applicable license terms, then you may not retain, install, activate or  */
/* otherwise use the software.                                              */
/*--------------------------------------------------------------------------*/

/**
 * @file  mcuxClKdfModes_Constants.h
 * @brief Constants for the mcuxClKdfModes component.
 */

#ifndef MCUXCLKDFMODES_CONSTANTS_H_
#define MCUXCLKDFMODES_CONSTANTS_H_

#include <mcuxCsslAnalysis.h>
#include <mcuxClConfig.h> // Exported features flags header

/**********************************************
 * CONSTANTS
 **********************************************/
/**
 * @defgroup mcuxClKdfModes_Constants mcuxClKdfModes_Constants
 * @brief Defines all constants of @ref mcuxClKdfModes
 * @ingroup mcuxClKdfModes
 * @{
 */

/** Bit-size of the binary repr. of the iteration counter r */
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT   (0u)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_MASK    ((uint32_t)0x3u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT)

#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_8       ((uint32_t)0u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_16      ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_24      ((uint32_t)2u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_32      ((uint32_t)3u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_SIZE_SHIFT)

/** Bit-size of the encoded output size */
MCUX_CSSL_ANALYSIS_START_PATTERN_DESCRIPTIVE_IDENTIFIER()
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT    (2u)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_MASK     ((uint32_t)0x3u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT)

#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_32       ((uint32_t)0u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_24       ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_16       ((uint32_t)2u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_8        ((uint32_t)3u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_REQUESTED_KEYLENGTH_ENCODING_SIZE_SHIFT)
MCUX_CSSL_ANALYSIS_STOP_PATTERN_DESCRIPTIVE_IDENTIFIER()

/** Endianess of iteration counter and encoded output size */
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_SHIFT          (4u)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_MASK           ((uint32_t)0x1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_SHIFT)

#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_BIG_ENDIAN     ((uint32_t)0u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_LITTLE_ENDIAN  ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_ENDIANESS_SHIFT)

/** If PRF input includes counter in Feedback and Double-Pipeline mode */
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_INCLUSION_SHIFT  (6u)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_INCLUSION_MASK   ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_INCLUSION_SHIFT)

#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_EXCLUDE_COUNTER          ((uint32_t)0u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_INCLUSION_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_INCLUDE_COUNTER          ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_COUNTER_INCLUSION_SHIFT)

/** KDF mode */
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_SHIFT               (7u)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_MASK                ((uint32_t)3u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_SHIFT)

#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_COUNTER             ((uint32_t)0u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_FEEDBACK            ((uint32_t)1u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_SHIFT)
#define MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_DOUBLE_PIPELINE     ((uint32_t)2u << MCUXCLKEY_DERIVATION_OPTIONS_NIST_SP800_108_MODE_SHIFT)




/** Max IV Lengths */

#define MCUXCLKEY_DERIVATION_NIST_SP800_56C_MAX_IVLENGTH           MCUXCLHASH_MAX_OUTPUT_SIZE
#define MCUXCLKEY_DERIVATION_NIST_SP800_56C_MAX_IVLENGTH_IN_WORDS (MCUXCLKEY_DERIVATION_NIST_SP800_56C_MAX_IVLENGTH / sizeof(uint32_t))

/** @} */

#endif /* MCUXCLKDFMODES_CONSTANTS_H_ */

